In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(r'C:\Users\Acer\Desktop\diploma\data\products.csv')
df.head(5)

,id,SKU,Name,Category,Brand,Seller,Color,Balance,Comments,Final Price,...,06.09.2021 Revenue,07.09.2021 Revenue,category_0,category_1,category_2,category_3,category_4,category_5,node_id,category
0,0,2237783,Туалетная вода древесный аромат/цитрусовый аромат,Красота/Парфюмерия/Мужские ароматы/Туалетная вода,ANTONIO BANDERAS,ООО Вайлдберриз,NaN,611,227,906,...,9060,9966,Красота,Парфюмерия,Мужские ароматы,Туалетная вода,NaN,NaN,31,beauty
1,1,15778086,Сахарная паста для шугаринга (депиляции) на фр...,Красота,Mivlane,ИП Ларченко Михаил Владиславович,NaN,1237,1388,357,...,65331,61404,Красота,NaN,NaN,NaN,NaN,NaN,31,beauty
2,2,21476793,Укрепляющее масло для ногтей со смолой мастико...,Красота/Профессиональная косметика/Масло,MILV,ИП Соколов Сергей Вадимович,NaN,106,31,210,...,420,840,Красота,Профессиональная косметика,Масло,NaN,NaN,NaN,31,beauty
3,3,4803247,"Интенсивный увлажняющий крем Soft для лица, ру...",Красота/Уход за кожей/Уход за телом/Крем,Nivea,ООО Вайлдберриз,NaN,3476,1065,216,...,36720,38232,Красота,Уход за кожей,Уход за телом,Крем,NaN,NaN,31,beauty
4,4,2147837,"Сменные кассеты Mach3 , 12 шт",Красота/Мужская линия/Для бритья/Кассета для б...,GILLETTE,ООО Вайлдберриз,черный,4973,1474,2041,...,87763,112255,Красота,Мужская линия,Для бритья,Кассета для бритв,NaN,NaN,31,beauty

In [13]:
df['shop_id'] = df['node_id']

df = df.drop(['node_id', 'category'], axis='columns')

In [14]:
columns = [
    'Average price',
    'Revenue potential',
    'Lost profit',
    'Lost profit percent',
    'Average if in stock',
    'Sales per day average'
]

for column in columns:
    df[column] = df[column].apply(lambda x: float(x.replace(',', '')))

In [15]:
df.dtypes.iloc[:50]

id                         int64
SKU                        int64
Name                      object
Category                  object
Brand                     object
Seller                    object
Color                     object
Balance                    int64
Comments                   int64
Final Price                int64
Max price                  int64
Min price                  int64
Average price            float64
Sales                      int64
Revenue                    int64
Revenue potential        float64
Lost profit              float64
Lost profit percent      float64
url                       object
thumb                     object
Days in stock              int64
Days with sales            int64
Average if in stock      float64
Rating                     int64
Basic Sale                 int64
Basic Sale Price           int64
Promo Sale                 int64
Base price                 int64
SPP                        int64
SPP Price                  int64
FBS                        int64
Category position          int64
Sales per day average    float64
09.08.2021 Sales           int64
10.08.2021 Sales           int64
11.08.2021 Sales           int64
12.08.2021 Sales           int64
13.08.2021 Sales           int64
14.08.2021 Sales           int64
15.08.2021 Sales           int64
16.08.2021 Sales           int64
17.08.2021 Sales           int64
18.08.2021 Sales           int64
19.08.2021 Sales           int64
20.08.2021 Sales           int64
21.08.2021 Sales           int64
22.08.2021 Sales           int64
23.08.2021 Sales           int64
24.08.2021 Sales           int64
25.08.2021 Sales           int64
dtype: object

In [16]:
df.to_csv(r'C:\Users\Acer\Desktop\diploma\data\products.csv', index=False)

In [3]:
import numpy as np

x = np.random.rand(50)
x

array([0.78911501, 0.93046583, 0.90830742, 0.17806676, 0.04133877,
       0.12791232, 0.22658477, 0.89265185, 0.79074934, 0.66978055,
       0.05091848, 0.05328476, 0.93048207, 0.64303932, 0.857631  ,
       0.99905032, 0.25198739, 0.46608467, 0.05916435, 0.28451433,
       0.15807501, 0.91715576, 0.6801605 , 0.23780535, 0.6802849 ,
       0.60859864, 0.76673791, 0.37896878, 0.97554263, 0.59602038,
       0.03890187, 0.29878698, 0.88332759, 0.90512059, 0.53626323,
       0.28971607, 0.66476564, 0.94269656, 0.85517609, 0.90691508,
       0.63410492, 0.53020732, 0.17059547, 0.75229934, 0.26184801,
       0.77941386, 0.80728804, 0.58797246, 0.6052057 , 0.56579374])

In [4]:
def formula(x):
    delta_T = 1/64

    sum_1 = 0
    for i in range(1, len(x)-1):
        value_1 = pow(
            ((x[i+1] - 2*x[i] + x[i-1])
             / pow(delta_T, 2)),
            2
        )

        sum_1 += value_1

    sum_2 = 0
    for i in range(1, len(x)-1):
        value_2 = pow(
            ((x[i-1] - x[i])
             / delta_T),
            2
        )

        sum_2 += value_2

    return sum_1 + sum_2/2

In [5]:
formula(x)

303088029.20854115

In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Acer\Desktop\development\github\diploma\data\data.csv")
df.head(5)

                                                Name Category
0  Крем-спрей для волос PERFECT HAIR многофункцио...  Красота
1  Средство для педикюра Гель для пяток с мочевин...  Красота
2  Средство для педикюра Гель для пяток с мочевин...  Красота
3  720 детских влажных салфеток с алоэ и витамино...  Красота
4  Массажер для спины / Массажер для шеи и плеч /...  Красота

In [3]:
df.iloc[:10].to_csv(r"C:\Users\Acer\Desktop\development\github\diploma\data\data.csv", index=False)